name: Pull Newer Code
on: 
  push:
    branches: [main]
    paths-ignore:
      - archive/**
      - CHANGELOG.md 
      - README.md
      - LICENCE
      - eslintrc.json
      - eslintignore
      - .prettierrc 
      - .gitignore
      - .husky
jobs:
  pull:
    name: Pull newer code
    runs-on: self-hosted

    steps: 
      - name: Backup Logs & Stop PM2
        run: |
              [ -d "~/actions-runner/chatbot-production-builds/InterChat/InterChat/logs/" ] && cp -r ~/actions-runner/chatbot-production-builds/InterChat/InterChat/logs/ ~/console-logs/$(date +'%Y-%m-%d-%M')
              pm2 stop interchat-prod

        # note to self: Checks out to ~/actions-runner/chatbot-production-builds/InterChat/InterChat/
      - name: Checkout repository
        uses: actions/checkout@v3

  restart:
      name: Build newer code and restart InterChat
      runs-on: self-hosted
  
      steps:   
        - name: Install dependencies
          run: npm install

        - name: Build code
          run: |
                npm run build --if-present
                cp ~/important/interchat-env .env
                
        - name: Deploy Commands
          run: npm run deploy -- -b
              
        - name: Prune Dev-dependencies
          run: npm prune --omit=dev

        - name: Restart InterChat 
          run: cd build/ && pm2 restart --update-env interchat-prod --ignore-watch logs --watch        
