
name: Restart ChatBot
on: push
  # push:
    # branches: [ main ]

jobs:
  deploy:
    name: Deploy & build code
    runs-on: self-hosted

    steps:      
      - name: Checkout repository
        uses: actions/checkout@v3
        # note to self: Files are stored in ~/actions-runner/chatbot-production-build/Discord-ChatBot/Discord-ChatBot 
      - name: Install dependencies
        run: npm i
        
      - name: Build code
        run: |
              pm2 stop build/src/index.js
              npm run build --if-present
              npm prune --omit=dev
        
      - name: Update env & pm2 
        run: | 
              cp ~/important/chatbot-env .env
              cd build/ && pm2 restart --update-env src/index.js --ignore-watch logs --watch        
