name: Deploy Code
on:
  push:
    branches: [main]
    paths-ignore:
      - archive/**
      - CHANGELOG.md
      - README.md
      - LICENCE
      - eslintrc.json
      - eslintignore
      - .prettierrc
      - .gitignore
      - .husky

concurrency:
    group: '${{ github.workflow }}-${{ github.ref }}'
    cancel-in-progress: true

jobs:
  build:
    name: Build updated code
    runs-on: self-hosted

    steps:
      - name: Backup Logs
        run: |
          if [ -d "logs/" ]; then
          cp -r logs/ ~/console-logs/$(date +'%Y-%m-%d-%M')
          fi

        # note to self: Checks out to ~/actions-runner/_work/InterChat/InterChat/
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          yarn
          npm rebuild @tensorflow/tfjs-node --build-from-source

      - name: Build code
        run: |
          yarn build
          cp ~/important/interchat-env .env

  restart:
    needs: [build]
    name: Restart bot
    runs-on: self-hosted

    steps:
      - name: Deploy Commands
        run: |
          yarn register:commands --public
          yarn register:commands --private

      - name: Mark build as successful
        run: touch build-successful.tmp
