name: Deploy Code
on: 
  push:
    branches: [main]
    paths-ignore:
      - archive/**
      - CHANGELOG.md 
      - README.md
      - LICENCE
      - eslintrc.json
      - eslintignore
      - .prettierrc 
      - .gitignore
      - .husky
jobs:
  build:
      name: Build updated code
      runs-on: self-hosted
  
      steps:
        # note to self: Checks out to ~/actions-runner/_work/InterChat/InterChat/
        - name: Backup Logs
          run: |
              if [ -d "logs/" ]; then
                cp -r logs/ ~/console-logs/$(date +'%Y-%m-%d-%M')
              fi
        
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Install dependencies
          run: npm install

        - name: Build code
          run: |
            cp ~/important/interchat-env .env
            npm run build -- --if-present
            npm rebuild @tensorflow/tfjs-node --build-from-source 
          # rebuilds tfjs-node for the current os

        - name: Initialize Git Submodules
          run: |
            rm -rf locales/
            git submodule update --init --recursive

        - name: Deploy Commands
          run: |
            npm run register:commands -- --public
            npm run register:commands -- --private
              
        - name: Prune Dev-dependencies
          run: npm prune --omit=dev

        - name: Mark build as successful 
          run: touch build-successful.tmp        
