name: Build
on: push
jobs:
  tests:
    name: Build Everything
    runs-on: self-hosted
    steps:
      - name: Run too many commands
        run: |
          cd ~/InterChat 
          git pull 
          yarn 
          npm rebuild @tensorflow/tfjs-node --build-from-source
          yarn prisma generate 
          yarn build 
          yarn register:commands --public 
          yarn register:commands --private 
      - name: Submodule Sync
        run: |
          git checkout main
          git pull
