name: Restart ChatBot
on: push
  # push:
    # branches: [ main ]

jobs:
  deploy:
    name: Deploy & build code
    runs-on: self-hosted
    defaults:
      run: 
        working-directory: ~/chatbot-builds/
      
    steps:      
      - name: Update code
        run: git pull origin main
        
      - name: Build code
        run: |
              npm run build
              npm prune --omit=dev

      - name: Start chatbot 
        run:  cd build/ && pm2 restart --update-env src/index.js --ignore-watch logs --watch
