name: Build & Run Code
on: push
  # push:
    # branches: [ main ]

jobs:
  build:
    name: Deploy & build code
    runs-on: self-hosted

    steps:      
      - name: Checkout repository
        uses: actions/checkout@v3
        # note to self: Files are stored in ~/actions-runner/chatbot-production-build/Discord-ChatBot/Discord-ChatBot 
        
      - name: Build code
        run: |
          npm install
          npm run build --if-present
          npm prune --omit=dev
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cb-build
          path: build
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: cb-build
          path: ~/chatbot-builds/
      
