
name: Deploy Code & Restart Bot
on: 
  push:
    branches: [main]
    paths-ignore:
      - archive/**
      - CHANGELOG.md 
      - README.md
      - LICENCE
      - eslintrc.json
      - eslintignore
      - .prettierrc 
      - .gitignore
      - .husky
jobs:
  build:
    name: Build newer code
    runs-on: self-hosted

    steps: 
      - name: Stop PM2
        run: pm2 stop interchat-prod

      - name: Checkout repository
        uses: actions/checkout@v3

        # note to self: Files are stored in ~/actions-runner/chatbot-production-build/Discord-ChatBot/Discord-ChatBot 
      - name: Install dependencies
        run: npm ci

      - name: Build code
        run: |
              npm run build --if-present
              npm prune --omit=dev

      - name: Update env & Restart bot 
        run: | 
              cp ~/important/chatbot-env .env
              cd build/ && pm2 restart --update-env interchat-prod --ignore-watch logs --watch        
