
name: Deploy & Build
on: push
  # push:
    # branches: [ main ]

jobs:
  deploy:
    name: Deploy & build code
    runs-on: self-hosted

    steps:      
      - name: Checkout repository
        uses: actions/checkout@v3
        # note to self: Files are stored in ~/actions-runner/chatbot-production-build/Discord-ChatBot/Discord-ChatBot 
      - name: Install dependencies
        run: npm i

      - name: Build code
        run: npm run build

      - name: Prune dev-Dependencies
        run: npm prune --omit=dev
   
      - name: Run the code
        run: pm2 start ./build/src/index.js --name chatbot-prod

        
