name: Lint
on: pull_request

jobs:
  tests:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun add eslint

      - name: Lint files
        run: bun eslint --no-fix src/
